[build]
    publish = "dist/web"
    command = "npm run build"
    functions = "dist/functions"

[context.branch-deploy]
    environment = { NODE_ENV = "development" }

[context.deploy-preview]
    environment = { NODE_ENV = "production", FAUNADB_SERVER_SECRET2 = "abcDP" }

[context.production]
    environment = { NODE_ENV = "production", FAUNADB_SERVER_SECRET2 = "abcPP" }