[build]
    publish = "dist/web"
    command = "npm run build"
    functions = "dist/functions"

[context.branch-deploy]
    environment = { NODE_ENV = "development", FAUNADB_SERVER_SECRET = FAUNADB_SERVER_SECRET2 }

[context.deploy-preview]
    environment = { NODE_ENV = "production" }

[context.production]
    environment = { NODE_ENV = "production" }