[build]
    publish = "dist/web"
    command = "npm run build"
    functions = "dist/functions"

[context.branch-deploy]
    environment = { NODE_ENV = "development" }

[context.deploy-preview]
    environment = { NODE_ENV = "production" }

[context.production]
    environment = { NODE_ENV = "production" }

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200